name: notebook tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build
      run: |
        set -xe
        python -VV
        pip install --upgrade pip
        pip install -e '.[test]'

    - name: Print versions
      run: |
        python -VV
        python -c "import jax; print('jax==', jax.__version__)"
        python -c "import jaxlib; print('jaxlib==', jaxlib.__version__)"

    - name: Intall Jupyter kernel
      run: |
        pip install ipykernel
        python -m ipykernel install --user --name=ott

    - name: Run notebook tests
      timeout-minutes: 60
      run: |
        python -m pytest -m notebook  --kernel-name=ott --notebook-cell-timeout=3600
